services:
  - type: web
    name: inventory-rdbms
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn web_app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3